import type { Metadata } from "next";
import {
  Inter,
  Permanent_Marker,
  Anton,
  Lobster,
  EB_Garamond,
} from "next/font/google";

import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });
const Permanent = Permanent_Marker({ weight: "400", subsets: ["latin"] });
const lob = Lobster({ weight: "400", subsets: ["latin"] });
const lob1 = EB_Garamond({ weight: "variable", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LK&CO.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lob1.className}>
        <div className=" text-skin-secondary  min-h-screen">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
